
TARGET_FLAGS=$(CC_SHARED) -DRegisterCodec=DllRegisterCodec -Iinclude -I../../../../

include ../../../../makefile.crc32
include ../../../../makefile.machine

LOCAL_LINK=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS)

include ../../../../makefile.glb
